[package]
name = "kraken_trading_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
krakenrs = "5.2.3"
rust_decimal = "1.28.1"
dotenv = "0.15.0"